spring:
  application:
    name: catalog-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalog}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    cache:
      type: redis

  mvc:
    static-path-pattern: /images/**
    resources:
      static-locations: file:./ops/storage/images/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.springframework: INFO