spring:
  datasource:
    url: ${CATALOG_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalog}
    username: ${CATALOG_DATASOURCE_USERNAME:postgres}
    password: ${CATALOG_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
cache:
  type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
